
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author HP
 */
public class CashierOperation extends javax.swing.JFrame {

        /**
         * Creates new form CashierOperation
         */
        public CashierOperation() {
                initComponents();
                setupTimeSpinner();
                getContentPane().setBackground(new java.awt.Color(230, 240, 255));
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblCashierOperation = new javax.swing.JLabel();
                lblProductID = new javax.swing.JLabel();
                lblQuantity = new javax.swing.JLabel();
                txtQuantity = new javax.swing.JTextField();
                lblPriceRM = new javax.swing.JLabel();
                lblPrice = new javax.swing.JLabel();
                btnAddItem = new javax.swing.JButton();
                lblCashReceived = new javax.swing.JLabel();
                btnConfirmPayment = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtDisplayReceipt = new javax.swing.JTextArea();
                txtProductName = new javax.swing.JTextField();
                btnDeleteItem = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();
                jDateChooser1 = new com.toedter.calendar.JDateChooser();
                lblPriceRM1 = new javax.swing.JLabel();
                lblPriceRM2 = new javax.swing.JLabel();
                txtCashReceive = new javax.swing.JTextField();
                SpinnerTime = new javax.swing.JSpinner();
                lblQuantity1 = new javax.swing.JLabel();
                lblID = new javax.swing.JLabel();
                btnSearch = new javax.swing.JButton();
                btnReset = new javax.swing.JButton();
                btnResetOutput = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                lblCashierOperation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lblCashierOperation.setText("Cashier Operation");

                lblProductID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblProductID.setText("Product ID          : ");

                lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblQuantity.setText("Quantity                    :");

                lblPriceRM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblPriceRM.setText("Price                          :");

                lblPrice.setText("RM");

                btnAddItem.setBackground(new java.awt.Color(102, 153, 255));
                btnAddItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnAddItem.setForeground(new java.awt.Color(255, 255, 255));
                btnAddItem.setText("Add Item");
                btnAddItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddItemActionPerformed(evt);
                        }
                });

                lblCashReceived.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblCashReceived.setText("Cash Received ( RM ): ");

                btnConfirmPayment.setBackground(new java.awt.Color(0, 0, 255));
                btnConfirmPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnConfirmPayment.setForeground(new java.awt.Color(255, 255, 255));
                btnConfirmPayment.setText("Confirm Payment");
                btnConfirmPayment.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnConfirmPaymentActionPerformed(evt);
                        }
                });

                txtDisplayReceipt.setColumns(20);
                txtDisplayReceipt.setRows(5);
                jScrollPane1.setViewportView(txtDisplayReceipt);

                btnDeleteItem.setBackground(new java.awt.Color(255, 0, 0));
                btnDeleteItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnDeleteItem.setForeground(new java.awt.Color(255, 255, 255));
                btnDeleteItem.setText("Delete Item");
                btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteItemActionPerformed(evt);
                        }
                });

                jButton1.setBackground(new java.awt.Color(102, 153, 255));
                jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setText("Back To Menu");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                lblPriceRM1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblPriceRM1.setText("Date                           :");

                lblPriceRM2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblPriceRM2.setText("Date                           :");

                txtCashReceive.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtCashReceiveActionPerformed(evt);
                        }
                });

                lblQuantity1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblQuantity1.setText("Product Name          :");

                btnSearch.setBackground(new java.awt.Color(102, 153, 255));
                btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnSearch.setForeground(new java.awt.Color(255, 255, 255));
                btnSearch.setText("Search Item");
                btnSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSearchActionPerformed(evt);
                        }
                });

                btnReset.setBackground(new java.awt.Color(102, 153, 255));
                btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnReset.setForeground(new java.awt.Color(255, 255, 255));
                btnReset.setText("Reset");
                btnReset.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnResetActionPerformed(evt);
                        }
                });

                btnResetOutput.setBackground(new java.awt.Color(102, 153, 255));
                btnResetOutput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnResetOutput.setForeground(new java.awt.Color(255, 255, 255));
                btnResetOutput.setText("Reset Receipt");
                btnResetOutput.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnResetOutputActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(85, 85, 85)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(btnDeleteItem)
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                .addComponent(SpinnerTime,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                158,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                                                                .addComponent(lblCashReceived,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                158,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                .addComponent(txtCashReceive,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                129,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                .addComponent(btnConfirmPayment)))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(40, 40, 40)
                                                                                                                                .addComponent(btnSearch)
                                                                                                                                .addGap(44, 44, 44)
                                                                                                                                .addComponent(btnAddItem)))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                28,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnReset)
                                                                                                .addGap(34, 34, 34))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(156, 156, 156)
                                                                                                .addComponent(btnResetOutput)
                                                                                                .addGap(61, 61, 61)
                                                                                                .addComponent(jButton1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                513,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(19, 19, 19))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(91, 91, 91)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(lblQuantity1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                123,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(lblPriceRM,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(lblQuantity,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                123,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(lblPriceRM1,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(lblPriceRM2,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                .addComponent(lblProductID)))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                                .addComponent(lblID,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                163,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(txtQuantity,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                163,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(lblPrice,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                163,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jDateChooser1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                163,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(txtProductName)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(185, 185, 185)
                                                                                                .addComponent(lblCashierOperation,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                187,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addComponent(lblCashierOperation)
                                                                .addGap(48, 48, 48)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jScrollPane1)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(lblProductID)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(txtProductName,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(lblQuantity1))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(lblID,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                27,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblQuantity)
                                                                                                                .addComponent(txtQuantity,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblPriceRM)
                                                                                                                .addComponent(lblPrice,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                27,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jDateChooser1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(lblPriceRM1))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblPriceRM2)
                                                                                                                .addComponent(SpinnerTime,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(34, 34, 34)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(btnSearch)
                                                                                                                .addComponent(btnAddItem)
                                                                                                                .addComponent(btnDeleteItem)
                                                                                                                .addComponent(btnReset))
                                                                                                .addGap(27, 27, 27)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblCashReceived)
                                                                                                                .addComponent(txtCashReceive,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(28, 28, 28)
                                                                                                .addComponent(btnConfirmPayment)
                                                                                                .addGap(37, 37, 37)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(btnResetOutput)
                                                                                                                .addComponent(jButton1))
                                                                                                .addGap(0, 224, Short.MAX_VALUE)))
                                                                .addGap(200, 200, 200)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void txtCashReceiveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCashReceiveActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtCashReceiveActionPerformed

        private void btnResetOutputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetOutputActionPerformed
                txtDisplayReceipt.setText("");
        }// GEN-LAST:event_btnResetOutputActionPerformed

        // initialize variables
        private String invoiceNo;
        private String productID;
        private int quantity;
        private double unitPrice;
        private double subTotal;
        private Timestamp saleDateTime;
        private Product prod; // store searched product
        private Sales sales;

        private ArrayList<Sales> salesList = new ArrayList<>();

        // Lambdas method
        private calTotal calcSubTotal;
        private InvoiceGenerator invoiceGen;
        private calTotal calcSST;
        // subtotal + total)
        private calTotal calcAdd;

        private void setupTimeSpinner() {
                SpinnerDateModel model = new SpinnerDateModel();
                SpinnerTime.setModel(model);
                JSpinner.DateEditor editor = new JSpinner.DateEditor(SpinnerTime, "hh:mm a");
                SpinnerTime.setEditor(editor);
        }

        private Timestamp getSaleDateTime() {

                // Get date from JDateChooser
                java.util.Date selectedDate = jDateChooser1.getDate();

                if (selectedDate == null) {
                        throw new IllegalStateException("Please select a date");
                }

                // Get time from Spinner
                java.util.Date selectedTime = (java.util.Date) SpinnerTime.getValue();

                // Combine using Calendar
                java.util.Calendar dateCal = java.util.Calendar.getInstance();
                dateCal.setTime(selectedDate);

                java.util.Calendar timeCal = java.util.Calendar.getInstance();
                timeCal.setTime(selectedTime);

                dateCal.set(java.util.Calendar.HOUR_OF_DAY,
                                timeCal.get(java.util.Calendar.HOUR_OF_DAY));
                dateCal.set(java.util.Calendar.MINUTE,
                                timeCal.get(java.util.Calendar.MINUTE));
                dateCal.set(java.util.Calendar.SECOND,
                                timeCal.get(java.util.Calendar.SECOND));
                dateCal.set(java.util.Calendar.MILLISECOND, 0);

                // 4. Convert to Timestamp
                return new Timestamp(dateCal.getTimeInMillis());
        }

        public void initializeSale() {

                // Lambdas
                // THIS WILL AUTO GENERATE INVOICE BASED ON THE MILISECONDS
                // NEVER BE SAME
                invoiceGen = () -> "INV" + System.currentTimeMillis();
                calcSST = (total, rate) -> total * rate;
                calcAdd = (a, b) -> a + b;
                calcSubTotal = (price, qty) -> price * qty;

                // Assign from GUI
                productID = prod.getProductID();

                quantity = Integer.parseInt(txtQuantity.getText().trim());

                // Assign from searched Product
                unitPrice = prod.getProductPrice();

                // Calculate subtotal (lambda)
                subTotal = calcSubTotal.calculate(unitPrice, quantity);

                // Combine date + time → Timestamp
                saleDateTime = getSaleDateTime();
                if (invoiceNo == null) {
                        invoiceNo = invoiceGen.generate();
                }

                sales = new Sales(invoiceNo, productID, quantity, unitPrice, subTotal, saleDateTime);
        }

        private double calculateSubtotal() {
                double subtotal = 0.0;
                for (Sales s : salesList) {
                        subtotal = calcAdd.calculate(subtotal, s.getSubTotal());
                }
                return subtotal;
        }

        private double calculateSST(double subtotal) {
                return calcSST.calculate(subtotal, 0.06);
        }

        private double calculateTotal(double subtotal, double sst) {
                return calcAdd.calculate(subtotal, sst);
        }

        private void rebuildReceipt() {

                txtDisplayReceipt.setText("");
                // ===== HEADER =====
                txtDisplayReceipt.append(String.format("%40s%n", "99 SPEEDMART UUM"));
                txtDisplayReceipt.append(String.format("%50s%n", "Fast • Fresh • Friendly Service\n\n"));
                txtDisplayReceipt.append(String.format("Invoice No   : %s%n", invoiceNo));
                txtDisplayReceipt.append(String.format("Date / Time  : %s%n", saleDateTime));
                txtDisplayReceipt.append("\n==============================================\n\n");

                txtDisplayReceipt.append(String.format("%-15s %15s %10s %10s%n",
                                "Item", "Qty", "Price", "Subtotal"));
                txtDisplayReceipt.append(
                                "\n------------------------------------------------------------------------------------\n\n");

                int no = 1;

                for (Sales s : salesList) {
                        txtDisplayReceipt.append(
                                        String.format("%-3d %s", no, s.toString()));
                        no++;
                }

                // TOTALS
                double subtotal = calculateSubtotal();
                double sst = calculateSST(subtotal);
                double total = calculateTotal(subtotal, sst);

                txtDisplayReceipt.append(
                                "\n------------------------------------------------------------------------------------\n\n");
                txtDisplayReceipt.append(String.format("Subtotal         : RM %.2f%n", subtotal));
                txtDisplayReceipt.append(String.format("SST (6%%)        : RM %.2f%n", sst));
                txtDisplayReceipt.append(String.format("TOTAL            : RM %.2f%n", total));
                txtDisplayReceipt.append(
                                "\n------------------------------------------------------------------------------------\n");

        }

        // ConfirmPayment
        private void btnConfirmPaymentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConfirmPaymentActionPerformed
                try {
                        // check receipt empty or not
                        if (salesList.isEmpty()) {
                                JOptionPane.showMessageDialog(this, "No items in receipt", "Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        // check if user enter or not cash
                        // trim to remove extra space begin &last text
                        if (txtCashReceive.getText().trim().isEmpty()) {
                                JOptionPane.showMessageDialog(this, "Please enter cash received", "Input Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        // convert string to double
                        double cashReceived = Double.parseDouble(txtCashReceive.getText().trim());

                        // use lambda to calculate
                        double subtotal = calculateSubtotal();
                        double sst = calculateSST(subtotal);
                        double total = calculateTotal(subtotal, sst);

                        // check if user enter enough or not to pay the items
                        if (cashReceived < total) {
                                JOptionPane.showMessageDialog(this, "Insufficient cash", "Payment Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        double balance = cashReceived - total;// cal balance

                        // Open Confirmation dialog
                        // yes/no
                        int choice = JOptionPane.showConfirmDialog(this,
                                        String.format(
                                                        "Subtotal : RM %.2f%n"
                                                                        + "SST (6%%) : RM %.2f%n"
                                                                        + "TOTAL     : RM %.2f%n%n"
                                                                        + "Cash      : RM %.2f%n"
                                                                        + "Balance   : RM %.2f%n%n"
                                                                        + "Confirm payment?",
                                                        subtotal, sst, total, cashReceived, balance),
                                        "Confirm Payment",
                                        JOptionPane.YES_NO_OPTION);

                        if (choice != JOptionPane.YES_OPTION) {
                                return;
                        }

                        // Save sales + reduce stock in db
                        for (Sales s : salesList) {// Loop through each item in the list
                                // call db method
                                DatabaseConnectionSales.addRecord(s);// save rec
                                DatabaseConnectionProduct.reduceStock(// update quantity (reduced based on quantity
                                                                      // item)
                                                s.getProductID(),
                                                s.getQuantity());
                        }

                        // Final receipt footer
                        txtDisplayReceipt.append(
                                        "------------------------------------------------------------------------------------\n\n");
                        txtDisplayReceipt.append(String.format("Cash Received : RM %.2f%n", cashReceived));
                        txtDisplayReceipt.append(String.format("Balance       : RM %.2f%n", balance));
                        txtDisplayReceipt.append(
                                        "------------------------------------------------------------------------------------\n");
                        txtDisplayReceipt.append("THANK YOU • PLEASE COME AGAIN\n");

                        // Reset transaction
                        salesList.clear();
                        invoiceNo = null;
                        txtCashReceive.setText("");

                        JOptionPane.showMessageDialog(this, "Payment successful", "Success",
                                        JOptionPane.INFORMATION_MESSAGE);

                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Cash received must be a valid number", "Input Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
        }// GEN-LAST:event_btnConfirmPaymentActionPerformed

        private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
                txtProductName.setText("");
                lblID.setText("");
                lblPrice.setText("RM");
                txtCashReceive.setText("");
        }// GEN-LAST:event_btnResetActionPerformed

        // Delete
        private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteItemActionPerformed

                try {
                        if (salesList.isEmpty()) {
                                JOptionPane.showMessageDialog(this,
                                                "No item to delete", "Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        // GET PRODUCT ID (NOT NAME!)
                        String productDelete = lblID.getText().trim();

                        if (productDelete.isEmpty()) {
                                JOptionPane.showMessageDialog(this,
                                                "Please search product first",
                                                "Input Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        int choice = JOptionPane.showConfirmDialog(this,
                                        "Are you sure you want to delete this item?",
                                        "Confirm Delete",
                                        JOptionPane.YES_NO_OPTION);

                        if (choice != JOptionPane.YES_OPTION)
                                return;

                        boolean removed = false;

                        Iterator<Sales> iterator = salesList.iterator();
                        while (iterator.hasNext()) {
                                Sales s = iterator.next();

                                // MATCH USING PRODUCT ID
                                if (s.getProductID().equalsIgnoreCase(productDelete)) {
                                        iterator.remove();
                                        removed = true;
                                        break;
                                }
                        }

                        if (!removed) {
                                JOptionPane.showMessageDialog(this,
                                                "Item not found in receipt",
                                                "Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        if (salesList.isEmpty()) {
                                invoiceNo = null;
                                txtDisplayReceipt.setText("");
                        } else {
                                rebuildReceipt();
                        }

                        JOptionPane.showMessageDialog(this,
                                        "Item deleted successfully",
                                        "Success",
                                        JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this,
                                        e.getMessage(),
                                        "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }

        }// GEN-LAST:event_btnDeleteItemActionPerformed

        private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSearchActionPerformed
                try {
                        String productName = txtProductName.getText().trim();

                        // check if input name empty
                        if (productName.isEmpty()) {
                                JOptionPane.showMessageDialog(this, "Please enter Product Name", "Input Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        // search product name in db product
                        prod = DatabaseConnectionProduct.searchName(productName);

                        // if not found
                        if (prod == null) {
                                JOptionPane.showMessageDialog(this, "Product not found", "Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        // DISPLAY product info
                        lblID.setText(prod.getProductID()); // show ID
                        lblPrice.setText(String.format("RM %.2f", prod.getProductPrice()));

                        JOptionPane.showMessageDialog(this, "Product found", "Success",
                                        JOptionPane.INFORMATION_MESSAGE);

                } catch (SQLException ex) {
                        // to show db error msg
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Error retrieving product from database", "Database Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }// GEN-LAST:event_btnSearchActionPerformed

        // to retun back to menu
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                new SpeedMartMenu().setVisible(true);
                this.dispose();
        }// GEN-LAST:event_jButton1ActionPerformed

        private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddItemActionPerformed
                try {

                        // check if product is search or not
                        if (prod == null) {
                                JOptionPane.showMessageDialog(this, "Please search product first", "Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        // chech empy or not
                        if (txtQuantity.getText().trim().isEmpty()) {
                                JOptionPane.showMessageDialog(this, "Please enter quantity", "Input Error",
                                                JOptionPane.ERROR_MESSAGE);
                                return;
                        }

                        initializeSale();

                        // check already generate or not invoice
                        if (invoiceNo == null) {
                                invoiceNo = invoiceGen.generate();
                        }

                        salesList.add(sales);// add record in list

                        rebuildReceipt();

                        txtQuantity.setText("");// clear quatitny fiel for next input

                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Quantity must be a number", "Input Error",
                                        JOptionPane.ERROR_MESSAGE);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
        }// GEN-LAST:event_btnAddItemActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(CashierOperation.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(CashierOperation.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(CashierOperation.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(CashierOperation.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new CashierOperation().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JSpinner SpinnerTime;
        private javax.swing.JButton btnAddItem;
        private javax.swing.JButton btnConfirmPayment;
        private javax.swing.JButton btnDeleteItem;
        private javax.swing.JButton btnReset;
        private javax.swing.JButton btnResetOutput;
        private javax.swing.JButton btnSearch;
        private javax.swing.JButton jButton1;
        private com.toedter.calendar.JDateChooser jDateChooser1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblCashReceived;
        private javax.swing.JLabel lblCashierOperation;
        private javax.swing.JLabel lblID;
        private javax.swing.JLabel lblPrice;
        private javax.swing.JLabel lblPriceRM;
        private javax.swing.JLabel lblPriceRM1;
        private javax.swing.JLabel lblPriceRM2;
        private javax.swing.JLabel lblProductID;
        private javax.swing.JLabel lblQuantity;
        private javax.swing.JLabel lblQuantity1;
        private javax.swing.JTextField txtCashReceive;
        private javax.swing.JTextArea txtDisplayReceipt;
        private javax.swing.JTextField txtProductName;
        private javax.swing.JTextField txtQuantity;
        // End of variables declaration//GEN-END:variables
}
