/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class SpeedMartMenu extends javax.swing.JFrame {

    /**
     * Creates new form SpeedMartGUI
     */
    public SpeedMartMenu() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(230, 240, 255));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTittle = new javax.swing.JLabel();
        btnStockManagement = new javax.swing.JButton();
        btnCashierOperation = new javax.swing.JButton();
        btnMonthlyStockReport = new javax.swing.JButton();
        btnMonthlySaleReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTittle.setText("99 SPEED MART MENU");

        btnStockManagement.setBackground(new java.awt.Color(51, 153, 255));
        btnStockManagement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStockManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnStockManagement.setText("Stock Management");
        btnStockManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockManagementActionPerformed(evt);
            }
        });

        btnCashierOperation.setBackground(new java.awt.Color(51, 153, 255));
        btnCashierOperation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCashierOperation.setForeground(new java.awt.Color(255, 255, 255));
        btnCashierOperation.setText("Cashier Operation");
        btnCashierOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierOperationActionPerformed(evt);
            }
        });

        btnMonthlyStockReport.setBackground(new java.awt.Color(51, 153, 255));
        btnMonthlyStockReport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMonthlyStockReport.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthlyStockReport.setText("Monthly Stock Report");
        btnMonthlyStockReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyStockReportActionPerformed(evt);
            }
        });

        btnMonthlySaleReport.setBackground(new java.awt.Color(51, 153, 255));
        btnMonthlySaleReport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMonthlySaleReport.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthlySaleReport.setText("Monthly Sale Report");
        btnMonthlySaleReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlySaleReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStockManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnMonthlyStockReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCashierOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMonthlySaleReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStockManagement)
                .addGap(18, 18, 18)
                .addComponent(btnCashierOperation)
                .addGap(18, 18, 18)
                .addComponent(btnMonthlyStockReport)
                .addGap(18, 18, 18)
                .addComponent(btnMonthlySaleReport)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStockManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockManagementActionPerformed
        // TODO add your handling code here:
        new StockManagement().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnStockManagementActionPerformed

    private void btnCashierOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierOperationActionPerformed
        // TODO add your handling code here:
        new CashierOperation().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCashierOperationActionPerformed

    private void btnMonthlyStockReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyStockReportActionPerformed
        // TODO add your handling code here:
        new MonthlyStockReport().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMonthlyStockReportActionPerformed

    private void btnMonthlySaleReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlySaleReportActionPerformed
        // TODO add your handling code here:
        new MonthlySaleReport().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMonthlySaleReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpeedMartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpeedMartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpeedMartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpeedMartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpeedMartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashierOperation;
    private javax.swing.JButton btnMonthlySaleReport;
    private javax.swing.JButton btnMonthlyStockReport;
    private javax.swing.JButton btnStockManagement;
    private javax.swing.JLabel lblTittle;
    // End of variables declaration//GEN-END:variables
}
