
import java.util.ArrayList;
import java.util.Collections;

import javax.swing.JOptionPane;

import java.sql.Date;
import java.sql.SQLException;

public class StockManagement extends javax.swing.JFrame {

        /**
         * Creates new form StockManagement
         */
        public StockManagement() {
                initComponents();
                getContentPane().setBackground(new java.awt.Color(230, 240, 255));

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                btnAdd = new javax.swing.JButton();
                lblTittle = new javax.swing.JLabel();
                lblProductID = new javax.swing.JLabel();
                lblProductName = new javax.swing.JLabel();
                lblPricePerUnit = new javax.swing.JLabel();
                lblStockQuantity = new javax.swing.JLabel();
                txtProductID = new javax.swing.JTextField();
                txtProductName = new javax.swing.JTextField();
                txtProductPrice = new javax.swing.JTextField();
                txtProductQuantity = new javax.swing.JTextField();
                btnUpdate = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                btnClear = new javax.swing.JButton();
                lblSearchProductBy = new javax.swing.JLabel();
                rbProductID = new javax.swing.JRadioButton();
                rbProductName = new javax.swing.JRadioButton();
                btnSearch = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                TADisplay = new javax.swing.JTextArea();
                btnBack = new javax.swing.JButton();
                txtSearchProductBy = new javax.swing.JTextField();
                lblStockQuantity1 = new javax.swing.JLabel();
                JDCProduct = new com.toedter.calendar.JDateChooser();
                btnDisplay = new javax.swing.JButton();
                CBSort = new javax.swing.JComboBox<>();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btnAdd.setBackground(new java.awt.Color(51, 153, 255));
                btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnAdd.setForeground(new java.awt.Color(255, 255, 255));
                btnAdd.setText("Add");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lblTittle.setText("Stock Management");

                lblProductID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblProductID.setText("Product ID         : ");

                lblProductName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblProductName.setText("Product Name   :");

                lblPricePerUnit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblPricePerUnit.setText("Price per Unit   :");

                lblStockQuantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblStockQuantity.setText("Stock Quantity :");

                btnUpdate.setBackground(new java.awt.Color(51, 153, 255));
                btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
                btnUpdate.setText("Update");
                btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUpdateActionPerformed(evt);
                        }
                });

                btnDelete.setBackground(new java.awt.Color(255, 0, 51));
                btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnDelete.setForeground(new java.awt.Color(255, 255, 255));
                btnDelete.setText("Delete");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                btnClear.setBackground(new java.awt.Color(51, 153, 255));
                btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnClear.setForeground(new java.awt.Color(255, 255, 255));
                btnClear.setText("Clear");
                btnClear.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnClearActionPerformed(evt);
                        }
                });

                lblSearchProductBy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblSearchProductBy.setText("Search Product By :");

                buttonGroup1.add(rbProductID);
                rbProductID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                rbProductID.setText("Product ID");

                buttonGroup1.add(rbProductName);
                rbProductName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                rbProductName.setText("Product Name");

                btnSearch.setBackground(new java.awt.Color(51, 153, 255));
                btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnSearch.setForeground(new java.awt.Color(255, 255, 255));
                btnSearch.setText("Search");
                btnSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSearchActionPerformed(evt);
                        }
                });

                TADisplay.setColumns(20);
                TADisplay.setRows(5);
                jScrollPane1.setViewportView(TADisplay);

                btnBack.setBackground(new java.awt.Color(51, 153, 255));
                btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnBack.setForeground(new java.awt.Color(255, 255, 255));
                btnBack.setText("Back To Menu");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                lblStockQuantity1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblStockQuantity1.setText(" Date                  :");

                btnDisplay.setBackground(new java.awt.Color(51, 153, 255));
                btnDisplay.setForeground(new java.awt.Color(255, 255, 255));
                btnDisplay.setText("Display Record");
                btnDisplay.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDisplayActionPerformed(evt);
                        }
                });

                CBSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product ID", "Product Name",
                                "Most Stock Quantity", "Least Stock Quantity", "Newest Date", "Oldest Date", " " }));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(192, 192, 192)
                                                                .addComponent(lblTittle,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                189,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 615, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(76, 76, 76)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblStockQuantity,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                112,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                false)
                                                                                                                                .addComponent(lblProductName,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                102,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(lblPricePerUnit,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)))
                                                                                                .addGap(24, 24, 24)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                false)
                                                                                                                .addComponent(txtProductID,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                279,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(txtProductQuantity,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(txtProductName,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                279,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(txtProductPrice,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(JDCProduct,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)))
                                                                                .addComponent(lblStockQuantity1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                112,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(lblSearchProductBy,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                130,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(btnAdd))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(txtSearchProductBy,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                249,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(6, 6, 6)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(rbProductID,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                98,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(btnClear)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addGap(9, 9, 9)
                                                                                                                                                                .addComponent(btnSearch)))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(btnUpdate)
                                                                                                                                                                .addGap(26, 26, 26)
                                                                                                                                                                .addComponent(btnDelete))
                                                                                                                                                .addComponent(rbProductName,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                129,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(btnBack)))))
                                                                                .addComponent(lblProductID,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                102,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                431,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(19, 19, 19))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addComponent(CBSort,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(btnDisplay)
                                                                                                                .addGap(178, 178,
                                                                                                                                178)))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(lblTittle,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                43,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblProductID)
                                                                                .addComponent(txtProductID,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnDisplay)
                                                                                .addComponent(CBSort,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblProductName)
                                                                                                                .addComponent(txtProductName,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblPricePerUnit)
                                                                                                                .addComponent(txtProductPrice,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblStockQuantity)
                                                                                                                .addComponent(txtProductQuantity,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(14, 14, 14)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(lblStockQuantity1)
                                                                                                                .addComponent(JDCProduct,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(45, 45, 45)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblSearchProductBy)
                                                                                                                .addComponent(txtSearchProductBy,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(rbProductID)
                                                                                                                .addComponent(rbProductName))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(btnSearch)
                                                                                                                .addComponent(btnUpdate)
                                                                                                                .addComponent(btnDelete)
                                                                                                                .addComponent(btnAdd))
                                                                                                .addGap(28, 28, 28)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(btnClear)
                                                                                                                .addComponent(btnBack)))
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                442,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(100, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed

                try {
                        initialize();
                        //check if field is empty or not
                        if (txtProductID.getText().isEmpty()
                                        || txtProductName.getText().isEmpty()
                                        || txtProductPrice.getText().isEmpty()
                                        || txtProductQuantity.getText().isEmpty()
                                        || JDCProduct.getDate() == null) {

                                JOptionPane.showMessageDialog(this, "Please fill in all fields.");
                                return;
                        }
                        //avoid id can be edit
                        txtProductID.setEditable(false);

                        //update record in db
                        int row = DatabaseConnectionProduct.updateData(prod);
                       
                        //check status update or not
                        if (row > 0) {
                                JOptionPane.showMessageDialog(this, "Record updated successfully!", "Success",JOptionPane.INFORMATION_MESSAGE);
                        } else {
                                JOptionPane.showMessageDialog(this, "Update failed. Record not found.", "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                        TADisplay.setText("UPDATE STOCK \n\n");
                        TADisplay.append(prod.toString());

                } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(this, "Please enter valid numeric values.", "Invalid Input",
                                        JOptionPane.ERROR_MESSAGE);

                } catch (SQLException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Failed to update record.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }// GEN-LAST:event_btnUpdateActionPerformed

        private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSearchActionPerformed

                try {
                        String keyword = txtSearchProductBy.getText().trim();
                        Product prod = null;

                        if (keyword.isEmpty()) {
                                JOptionPane.showMessageDialog(this, "Please enter a search value.");
                                return;
                        }

                        // Search by Product ID
                        if (rbProductID.isSelected()) {
                                prod = DatabaseConnectionProduct.searchID(keyword);
                                txtProductID.setEditable(false);

                        } // Search by Product Name
                        else if (rbProductName.isSelected()) {
                                prod = DatabaseConnectionProduct.searchName(keyword);
                                txtProductID.setEditable(false);

                        } else {
                                JOptionPane.showMessageDialog(this, "Please select search type.");
                                return;
                        }

                        // If product found
                        if (prod != null) {
                                txtProductID.setText(prod.getProductID());
                                txtProductName.setText(prod.getProductName());
                                txtProductPrice.setText(String.valueOf(prod.getProductPrice()));
                                txtProductQuantity.setText(String.valueOf(prod.getProductQuantity()));

                                // convert sql.Date → util.Date for JDateChooser
                                JDCProduct.setDate(new java.util.Date(prod.getProductDate().getTime()));
                                TADisplay.setText("STOCK FOUND \n\n");
                                TADisplay.append(prod.toString());

                                JOptionPane.showMessageDialog(this, "Product found.");
                        } else {
                                JOptionPane.showMessageDialog(this, "Product not found.");
                        }

                } catch (SQLException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(this,
                                        "Error while searching product.",
                                        "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }

        }// GEN-LAST:event_btnSearchActionPerformed

        private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDisplayActionPerformed
                try {
                        // clear text area first
                        TADisplay.setText("STOCK LIST\n-----------------------------");

                        // get data from database
                        ArrayList<Product> productList = DatabaseConnectionProduct.readData();
                        String sortType = CBSort.getSelectedItem().toString();

                        // sort prod type from combo bx
                        Collections.sort(productList, new ProductSort(sortType));
                        // display each product
                        for (Product p : productList) {
                                TADisplay.append(p.toString());
                        }

                } catch (SQLException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Failed to retrieve data from database.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }// GEN-LAST:event_btnDisplayActionPerformed

        // instance variable
        private String productID, productName;
        private double productPrice;
        private int productQuantity;
        private Date productDate;

        ArrayList<Product> productList = new ArrayList();// arayylist to stored all the data
        Product prod;

        public void initialize() {

                productID = txtProductID.getText();
                productName = txtProductName.getText();
                productPrice = Double.parseDouble(txtProductPrice.getText());
                productQuantity = Integer.parseInt(txtProductQuantity.getText());

                java.util.Date utilDate = (java.util.Date) JDCProduct.getDate();
                productDate = new java.sql.Date(utilDate.getTime());

                prod = new Product(productID, productName, productPrice, productQuantity, productDate);
        }

        private void refreshRecord() {
                txtProductID.setText("");
                txtProductName.setText("");
                txtProductPrice.setText("");
                txtProductQuantity.setText("");
                JDCProduct.setDate(null);
        }

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed

                try {
                        initialize();

                        // if user not enter any input
                        if (txtProductID.getText().isEmpty()
                                        || txtProductName.getText().isEmpty()
                                        || txtProductPrice.getText().isEmpty()
                                        || txtProductQuantity.getText().isEmpty()
                                        || JDCProduct.getDate() == null) {

                                JOptionPane.showMessageDialog(this, "Please fill in all fields.");

                                return;
                        }

                        DatabaseConnectionProduct.addRecord(prod);

                        JOptionPane.showMessageDialog(this, "Record added successfully!", "Success",
                                        JOptionPane.INFORMATION_MESSAGE);
                        TADisplay.setText("ADD NEW STOCK \n");
                        TADisplay.append(prod.toString());

                } catch (SQLException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Failed to add record.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(this, "Please check your input", "Invalid Input",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }// GEN-LAST:event_btnAddActionPerformed

        // DELETE===
        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
                try {
                        String DeleteProduct = txtProductID.getText().trim();

                        if (DeleteProduct.isEmpty()) {
                                JOptionPane.showMessageDialog(this,
                                                "Please enter or search a Product ID to delete.",
                                                "Missing Product ID",
                                                JOptionPane.WARNING_MESSAGE);
                                return;
                        }

                        int choice = JOptionPane.showConfirmDialog(
                                        this,
                                        "Are you sure you want to delete this product?",
                                        "Confirm Delete",
                                        JOptionPane.YES_NO_OPTION,
                                        JOptionPane.WARNING_MESSAGE);

                        if (choice != JOptionPane.YES_OPTION) {
                                return;
                        }

                        int row = DatabaseConnectionProduct.DeleteRecord(DeleteProduct);

                        if (row > 0) {
                                JOptionPane.showMessageDialog(this,
                                                "Record deleted successfully!",
                                                "Success",
                                                JOptionPane.INFORMATION_MESSAGE);

                                refreshRecord();
                                btnDisplayActionPerformed(null);

                        } else {
                                JOptionPane.showMessageDialog(this,
                                                "Delete failed. Record not found.",
                                                "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }

                } catch (SQLException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(this,
                                        "Failed to delete record.",
                                        "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }// GEN-LAST:event_btnDeleteActionPerformed

        private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearActionPerformed
                txtProductID.setText("");
                txtProductName.setText("");
                txtProductPrice.setText("");
                txtProductQuantity.setText("");
                JDCProduct.setDate(null); // reset date chooser
                TADisplay.setText("");
                txtSearchProductBy.setText("");
        }// GEN-LAST:event_btnClearActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
                // TODO add your handling code here:
                new SpeedMartMenu().setVisible(true);
                this.dispose();

        }// GEN-LAST:event_btnBackActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new StockManagement().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox<String> CBSort;
        private com.toedter.calendar.JDateChooser JDCProduct;
        private javax.swing.JTextArea TADisplay;
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnClear;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnDisplay;
        private javax.swing.JButton btnSearch;
        private javax.swing.JButton btnUpdate;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblPricePerUnit;
        private javax.swing.JLabel lblProductID;
        private javax.swing.JLabel lblProductName;
        private javax.swing.JLabel lblSearchProductBy;
        private javax.swing.JLabel lblStockQuantity;
        private javax.swing.JLabel lblStockQuantity1;
        private javax.swing.JLabel lblTittle;
        private javax.swing.JRadioButton rbProductID;
        private javax.swing.JRadioButton rbProductName;
        private javax.swing.JTextField txtProductID;
        private javax.swing.JTextField txtProductName;
        private javax.swing.JTextField txtProductPrice;
        private javax.swing.JTextField txtProductQuantity;
        private javax.swing.JTextField txtSearchProductBy;
        // End of variables declaration//GEN-END:variables
}
