
import java.util.ArrayList;
import java.util.Collections;

import javax.swing.JOptionPane;

import java.sql.Date;
import java.sql.SQLException;

public class StockManagement extends javax.swing.JFrame {

    /**
     * Creates new form StockManagement
     */
    public StockManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnAdd = new javax.swing.JButton();
        lblTittle = new javax.swing.JLabel();
        lblProductID = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblPricePerUnit = new javax.swing.JLabel();
        lblStockQuantity = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtProductPrice = new javax.swing.JTextField();
        txtProductQuantity = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblSearchProductBy = new javax.swing.JLabel();
        rbProductID = new javax.swing.JRadioButton();
        rbProductName = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TADisplay = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        txtSearchProductBy = new javax.swing.JTextField();
        lblStockQuantity1 = new javax.swing.JLabel();
        JDCProduct = new com.toedter.calendar.JDateChooser();
        btnDisplay = new javax.swing.JButton();
        CBSort = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTittle.setText("Stock Management");

        lblProductID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductID.setText("Product ID         : ");

        lblProductName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductName.setText("Product Name   :");

        lblPricePerUnit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPricePerUnit.setText("Price per Unit   :");

        lblStockQuantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStockQuantity.setText("Stock Quantity :");

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Update");

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblSearchProductBy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearchProductBy.setText("Search Product By :");

        buttonGroup1.add(rbProductID);
        rbProductID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbProductID.setText("Product ID");

        buttonGroup1.add(rbProductName);
        rbProductName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbProductName.setText("Product Name");

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        TADisplay.setColumns(20);
        TADisplay.setRows(5);
        jScrollPane1.setViewportView(TADisplay);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back To Menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblStockQuantity1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStockQuantity1.setText(" Date                  :");

        btnDisplay.setText("Display Record");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        CBSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product ID", "Product Name",
                "Most Stock Quantity", "Least Stock Quantity", "Newest Date", "Oldest Date", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 189,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 150, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblSearchProductBy,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtSearchProductBy,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 249,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(rbProductID,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                98,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(btnSearch))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(btnUpdate)
                                                                                                .addGap(26, 26, 26)
                                                                                                .addComponent(
                                                                                                        btnDelete))
                                                                                        .addComponent(rbProductName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                129,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(btnDisplay)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(btnClear))))))
                                        .addComponent(CBSort, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblStockQuantity,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 112,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(lblProductName,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 102,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(lblPricePerUnit,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)))
                                                .addGap(24, 24, 24)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(txtProductID,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 279,
                                                                Short.MAX_VALUE)
                                                        .addComponent(txtProductQuantity,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtProductName,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 279,
                                                                Short.MAX_VALUE)
                                                        .addComponent(txtProductPrice,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(JDCProduct,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(127, 127, 127)
                                                .addComponent(btnBack))
                                        .addComponent(lblStockQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 112,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 102,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd)
                                .addGap(152, 152, 152)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblProductID)
                                        .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblProductName)
                                        .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPricePerUnit)
                                        .addComponent(txtProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblStockQuantity)
                                        .addComponent(txtProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblStockQuantity1)
                                        .addComponent(JDCProduct, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSearchProductBy)
                                        .addComponent(txtSearchProductBy, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbProductID)
                                        .addComponent(rbProductName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSearch)
                                        .addComponent(btnUpdate)
                                        .addComponent(btnDelete))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDisplay)
                                        .addComponent(CBSort, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnClear))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBack)
                                .addGap(12, 12, 12)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSearchActionPerformed

        try {
            String keyword = txtSearchProductBy.getText().trim();
            Product prod = null;

            if (keyword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a search value.");
                return;
            }

            // Search by Product ID
            if (rbProductID.isSelected()) {
                prod = DatabaseConnection.searchID(keyword);
            }
            // Search by Product Name
            else if (rbProductName.isSelected()) {
                prod = DatabaseConnection.searchName(keyword);
            } else {
                JOptionPane.showMessageDialog(this, "Please select search type.");
                return;
            }

            // If product found
            if (prod != null) {
                txtProductID.setText(prod.getProductID());
                txtProductName.setText(prod.getProductName());
                txtProductPrice.setText(String.valueOf(prod.getProductPrice()));
                txtProductQuantity.setText(String.valueOf(prod.getProductQuantity()));

                // convert sql.Date → util.Date for JDateChooser
                JDCProduct.setDate(new java.util.Date(prod.getProductDate().getTime()));
                TADisplay.setText("STOCK FOUND \n\n");
                TADisplay.append(prod.toString());

                JOptionPane.showMessageDialog(this, "Product found.");
            } else {
                JOptionPane.showMessageDialog(this, "Product not found.");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error while searching product.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_btnSearchActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDisplayActionPerformed
        try {
            // clear text area first
            TADisplay.setText("STOCK LIST\n-----------------------------");

            // get data from database
            ArrayList<Product> productList = DatabaseConnection.readData();
            String sortType = CBSort.getSelectedItem().toString();

            Collections.sort(productList, new ProductSort(sortType));
            // display each product
            for (Product p : productList) {
                TADisplay.append(p.toString());
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to retrieve data from database.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnDisplayActionPerformed

    // instance variable
    private String productID, productName;
    private double productPrice;
    private int productQuantity;
    private Date productDate;

    ArrayList<Product> productList = new ArrayList();// arayylist to stored all the data
    Product prod;

    public void initialize() {
        productID = txtProductID.getText();
        productName = txtProductName.getText();
        productPrice = Double.parseDouble(txtProductPrice.getText());
        productQuantity = Integer.parseInt(txtProductQuantity.getText());

        java.util.Date utilDate = (java.util.Date) JDCProduct.getDate();
        productDate = new java.sql.Date(utilDate.getTime());

        prod = new Product(productID, productName, productPrice, productQuantity, productDate);
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed

        try {
            initialize();

            // if user not enter any input
            if (txtProductID.getText().isEmpty()
                    || txtProductName.getText().isEmpty()
                    || txtProductPrice.getText().isEmpty()
                    || txtProductQuantity.getText().isEmpty()
                    || JDCProduct.getDate() == null) {

                JOptionPane.showMessageDialog(this, "Please fill in all fields.");

                return;
            }

            DatabaseConnection.addRecord(prod);

            JOptionPane.showMessageDialog(this, "Record added successfully!", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            TADisplay.setText("ADD NEW STOCK \n");
            TADisplay.append(prod.toString());

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to add record.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please check your input", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearActionPerformed
        txtProductID.setText("");
        txtProductName.setText("");
        txtProductPrice.setText("");
        txtProductQuantity.setText("");
        JDCProduct.setDate(null); // reset date chooser
        TADisplay.setText("");
        txtSearchProductBy.setText("");
    }// GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new SpeedMartMenu().setVisible(true);
        this.dispose();

    }// GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBSort;
    private com.toedter.calendar.JDateChooser JDCProduct;
    private javax.swing.JTextArea TADisplay;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPricePerUnit;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblSearchProductBy;
    private javax.swing.JLabel lblStockQuantity;
    private javax.swing.JLabel lblStockQuantity1;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JRadioButton rbProductID;
    private javax.swing.JRadioButton rbProductName;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtProductQuantity;
    private javax.swing.JTextField txtSearchProductBy;
    // End of variables declaration//GEN-END:variables
}
